repository_class: 'Woli::Repositories::Files'
repository_config:
  path: ~/.woli/diary
  entry_extension: md

editor:

notification:
  missing_entries:
    days: 1
    command: "notify-send 'Woli diary is missing entries.'"
