repository_class: 'Woli::Repositories::Files'
repository_config:
  path: ~/.woli/diary
  entry_extension: md

editor:
edit_entry_extension: md

notification:
  missing_entries:
    days: 1
    command: "notify-send 'Woli diary is hungry for entries.'"
